In [1]:

import pandas as pd

data = {
    " Student Name ": [
        "Sai", "Ravi", "Anu", "Kiran",
        "Ravi", "Meena", "Arjun", "Divya"
    ],
    "Age ": [
        "20", "21", None, "20",
        "21", "twenty", "22", "19"
    ],
    " Marks ": [
        "85", "90", "78", None,
        "90", "88", None, "92"
    ],
    "Department ": [
        "CSE", "ECE", "CSE", "IT",
        "ECE", "CSE", "ECE", None
    ]
}

df = pd.DataFrame(data)

df.to_csv("student_data_raw.csv", index=False)

print("Sample dataset created successfully!")
print(df)

Sample dataset created successfully!
   Student Name     Age   Marks  Department
0            Sai      20      85         CSE
1           Ravi      21      90         ECE
2            Anu     NaN      78         CSE
3          Kiran      20     NaN          IT
4           Ravi      21      90         ECE
5          Meena  twenty      88         CSE
6          Arjun      22     NaN         ECE
7          Divya      19      92         NaN

In [2]:

df = pd.read_csv("student_data_raw.csv")

print("First five rows:")
display(df.head())

print("\nDataset shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

First five rows:

   Student Name  Age    Marks  Department
0            Sai   20     85.0         CSE
1           Ravi   21     90.0         ECE
2            Anu  NaN     78.0         CSE
3          Kiran   20      NaN          IT
4           Ravi   21     90.0         ECE

Dataset shape:
(8, 4)

Column names:
[' Student Name ', 'Age ', ' Marks ', 'Department ']

Data types:
 Student Name         str
Age                   str
 Marks            float64
Department            str
dtype: object

In [3]:

print("Missing values in each column:")
print(df.isnull().sum())

print("\nTotal missing values:")
print(df.isnull().sum().sum())

print("\nNumber of duplicate rows:")
print(df.duplicated().sum())

Missing values in each column:
 Student Name     0
Age               1
 Marks            2
Department        1
dtype: int64

Total missing values:
4

Number of duplicate rows:
1

In [4]:

# Remove extra spaces and standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print("Cleaned column names:")
print(df.columns.tolist())

display(df.head())

Cleaned column names:
['student_name', 'age', 'marks', 'department']

  student_name  age  marks department
0          Sai   20   85.0        CSE
1         Ravi   21   90.0        ECE
2          Anu  NaN   78.0        CSE
3        Kiran   20    NaN         IT
4         Ravi   21   90.0        ECE

In [5]:

# Convert age and marks to numeric values
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["marks"] = pd.to_numeric(df["marks"], errors="coerce")

# Fill missing numerical values with the median
df["age"] = df["age"].fillna(df["age"].median())
df["marks"] = df["marks"].fillna(df["marks"].median())

# Fill missing department with the most frequent department
df["department"] = df["department"].fillna(df["department"].mode()[0])

print("Missing values after handling:")
print(df.isnull().sum())

display(df)

Missing values after handling:
student_name    0
age             0
marks           0
department      0
dtype: int64

  student_name   age  marks department
0          Sai  20.0   85.0        CSE
1         Ravi  21.0   90.0        ECE
2          Anu  20.5   78.0        CSE
3        Kiran  20.0   89.0         IT
4         Ravi  21.0   90.0        ECE
5        Meena  20.5   88.0        CSE
6        Arjun  22.0   89.0        ECE
7        Divya  19.0   92.0        CSE

In [6]:

before = len(df)

df = df.drop_duplicates()

after = len(df)

print("Rows before removing duplicates:", before)
print("Rows after removing duplicates:", after)
print("Duplicate rows remaining:", df.duplicated().sum())

Rows before removing duplicates: 8
Rows after removing duplicates: 7
Duplicate rows remaining: 0

In [7]:

# Convert age to integer
df["age"] = df["age"].round().astype(int)

# Save the cleaned dataset
df.to_csv("cleaned_student_data.csv", index=False)

print("Cleaned dataset saved successfully!")
print("\nFinal dataset information:")
df.info()

print("\nFinal dataset:")
display(df)

print("\nMissing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Cleaned dataset saved successfully!

Final dataset information:
<class 'pandas.DataFrame'>
Index: 7 entries, 0 to 7
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_name  7 non-null      str
 1   age           7 non-null      int64
 2   marks         7 non-null      float64
 3   department    7 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 332.0 bytes

Final dataset:

  student_name  age  marks department
0          Sai   20   85.0        CSE
1         Ravi   21   90.0        ECE
2          Anu   20   78.0        CSE
3        Kiran   20   89.0         IT
5        Meena   20   88.0        CSE
6        Arjun   22   89.0        ECE
7        Divya   19   92.0        CSE

Missing values: 0
Duplicate rows: 0