In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.3

In [2]:
import pandas as pd

df = pd.read_csv("student_data.csv")

df

   Student_ID    Name  Age  Gender  Marks  Attendance
0           1   Aarav   19    Male     85          92
1           2  Ananya   20  Female     78          88
2           3   Rahul   19    Male     45          70
3           4   Priya   20  Female     91          95
4           5   Kiran   19    Male     67          82
5           6   Sneha   20  Female     55          76
6           7   Arjun   19    Male     73          85
7           8   Divya   20  Female     88          91
8           9   Rohan   19    Male     39          65
9          10   Meena   20  Female     95          97

In [3]:
df.head()

   Student_ID    Name  Age  Gender  Marks  Attendance
0           1   Aarav   19    Male     85          92
1           2  Ananya   20  Female     78          88
2           3   Rahul   19    Male     45          70
3           4   Priya   20  Female     91          95
4           5   Kiran   19    Male     67          82

In [4]:
df.tail()

   Student_ID   Name  Age  Gender  Marks  Attendance
5           6  Sneha   20  Female     55          76
6           7  Arjun   19    Male     73          85
7           8  Divya   20  Female     88          91
8           9  Rohan   19    Male     39          65
9          10  Meena   20  Female     95          97

In [5]:
#Check rows and columns
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 10
Number of columns: 6

In [6]:
df.shape

(10, 6)

In [7]:
#Find Missing Values
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
Marks         0
Attendance    0
dtype: int64

In [8]:
#Filter the data
#Students who scored above 70
df[df["Marks"] > 70]
#Students who scored below 50
df[df["Marks"] < 50]
#Students with attendance above 90
df[df["Attendance"] > 90]

   Student_ID   Name  Age  Gender  Marks  Attendance
0           1  Aarav   19    Male     85          92
3           4  Priya   20  Female     91          95
7           8  Divya   20  Female     88          91
9          10  Meena   20  Female     95          97

In [9]:
#Multiple conditions
df[(df["Marks"] > 70) & (df["Attendance"] > 85)]

   Student_ID    Name  Age  Gender  Marks  Attendance
0           1   Aarav   19    Male     85          92
1           2  Ananya   20  Female     78          88
3           4   Priya   20  Female     91          95
7           8   Divya   20  Female     88          91
9          10   Meena   20  Female     95          97

In [10]:
#Summary Statistics
df.describe()

       Student_ID        Age      Marks  Attendance
count    10.00000  10.000000  10.000000   10.000000
mean      5.50000  19.500000  71.600000   84.100000
std       3.02765   0.527046  19.670621   10.774971
min       1.00000  19.000000  39.000000   65.000000
25%       3.25000  19.000000  58.000000   77.500000
50%       5.50000  19.500000  75.500000   86.500000
75%       7.75000  20.000000  87.250000   91.750000
max      10.00000  20.000000  95.000000   97.000000

In [11]:
#simple analysis
average_marks = df["Marks"].mean()

print("Average Marks:", average_marks)
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())
print("Average Attendance:", df["Attendance"].mean())

Average Marks: 71.6
Highest Marks: 95
Lowest Marks: 39
Average Attendance: 84.1